### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by egorzot** [bitrix-expert/monolog-adapter#3]
Периодически выскакивает ошибка

> Declaration of Bex\Monolog\ExceptionHandlerLog::write() must be compatible with Bitrix\Main\Diag\ExceptionHandlerLog::write($exception, $logType) in /home/bitrix/www/vendor/bitrix-expert/monolog-adapter/src/ExceptionHandlerLog.php on line 0

Разница между Bitrix\Main\Diag\ExceptionHandlerLog::write и Bex\Monolog\ExceptionHandlerLog::write в том, что у Bex\Monolog\ExceptionHandlerLog::write указан тип параметра \Exception  $exception, а у Bitrix\Main\Diag\ExceptionHandlerLog::write нет

main версии 16.5.4
php 5.6.24

**Comment by egorzot** [comment]
Похоже данная ошибка появляется только при определенном неправильном конфиге. 
В моем случае был неправильно определен форматтер одного из хэндлеров.

**Comment by niksamokhvalov** [comment]
Действительно, в новой версии битриксоиды убрали типизацию параметра в \Bitrix\Main\Diag\ExceptionHandlerLog::write.
